Add initialize function for EPS sensors
SpaceTeam/STS1_COBC_SW pull request #252
Opened 2024-02-11 02:38 UTC by danielschloms

### Description
This PR adds functionality to initialize the EPS ADCs for the COBC, including the necessary pin definitions.

Fixes #212

2024-02-11 02:39 UTC, danielschloms commented
There are still 2 unresolved issues:
- This cannot be tested until the COBC is available again.
- The FRAM shares the same SPI, but uses a higher baudrate. This does not seem to be okay, as RODOS does not change the baudrate before transferring data, and the max. baudrate in the datasheet is 10 MHz (FRAM uses 12 MHz).

2024-02-21 12:15 UTC, danielschloms commented on Sts1CobcSw/Periphery/Eps.cpp
> +namespace sts1cobcsw::periphery::eps
Remove periphery from namespace (see #139)

2024-03-03 17:09 UTC, PatrickKa requested changes

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Hal/IoNames.hpp
> +inline constexpr auto epsCs3Pin = pb5;
I would rename them to `epsAdc4CsPin`, etc. because then you don't need the conversion from CS pin to ADC in the table in Eps.cpp.

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.cpp
> +constexpr auto setupRegister = 1_b << 6;
You have a function just for this register so this variable doesn't need to be global but can be moved to that function.

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.cpp
> +auto cs3GpioPin = hal::GpioPin(hal::epsCs3Pin);
Rename these as well: `adc4CsGpioPin`, ...

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.cpp
> +auto epsSpi = RODOS::HAL_SPI(
Rename this to just `spi`.

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.cpp
> +auto SetSetupRegister(hal::GpioPin * adcCsPin) -> void;
The name sounds a bit strange. I think something like `ConfigureSetupRegister()` or just `SetUpAdc()` is better.

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.cpp
> +    hal::Initialize(&epsSpi, baudrate);
I think we talked about this and agreed on just using 6 MHz for the communication with both the ADCs and the FRAM.

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.cpp
> +    constexpr auto referenceMode = 0b00_b;
Shouldn't this be shifted by 2?

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.cpp
> +    auto setupData = 0_b | setupRegister | clockMode | referenceMode;
Remove the leading 0. Don't see why we need it.

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.hpp
> +
2 blank lines after the `#inlcude` block, even if it's empty.

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.cpp
> +
2 blank lines after the `#inlcude` block

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.cpp
> +}
Files must end with a blank line. Unfortunately, only clang-format 16 adds an option for that (https://releases.llvm.org/16.0.0/tools/clang/docs/ClangFormatStyleOptions.html#insertnewlineateof) but we still use clang-format 15.

2024-03-03 17:09 UTC, PatrickKa commented on Sts1CobcSw/Periphery/Eps.hpp
> +}
Files must end with a blank line.

2024-03-03 21:17 UTC, danielschloms commented on Sts1CobcSw/Periphery/Eps.cpp
> +    constexpr auto referenceMode = 0b00_b;
If it's zero it wouldn't matter, but I have rewritten it in a clearer way.

2024-03-05 19:38 UTC, PatrickKa approved these changes

2024-03-05 19:52 UTC, merged